### ISSUE TITLE
文档和demo都不详细，感觉越看越晕，要是能更新下说明文档就更好了

### ISSUE THREAD

**Issue by Nodewebzsz** [tolerance-go/weappx#10]

**Comment by Nodewebzsz** [comment]
这个文档我试过了，还是报错啊，VM8682:1 thirdScriptError
Cannot read property 'catch' of undefined;at pages/index/index page plus function
TypeError: Cannot read property 'catch' of undefined
    at Object.dispatch (http://127.0.0.1:48026/appservice/npm/weappx/lib/middlewares/tunk.js:33:11)
    at Object._this.dispatcher.(anonymous function).(anonymous function) [as setData]

**Comment by tolerance-go** [comment]
actions 需要返回一个 async function，或者说返回的函数调用结果得是一个 promise，大概这里的 catch 报错就是这个原因。不过例子里面没有用到 model.actions 呀，最好贴下使用代码

**Comment by tolerance-go** [comment]
在 async 函数内部，需要调用 dispatcher 继续派发 mutation action 去修改 state，请参考使用案例

**Comment by tolerance-go** [comment]
1: 在 actions 内部调用 dispatcher 去派发当前 model 的 action，可以省略 count

> dispatcher - 参考 store.dispatcher，当前 namespace 下的所有 actionCreator，直接挂载于 dispatcher 上，也就是说可以省略 namespace 直接调用: dispatcher[namespace][actioncreatorname]；如果当前 namespace 下的 actionCreatorName 和全局其他 namespace 名称冲突，保留全局，并发出警告

2: 如果是修改替换 state 你需要去 return 它

```js
mutations: {
   test: (state, payload) => {
      state = {
          ...state,
          ...payload
      }
      return state
   }
}
```

> reducer 内部使用 immer 进行包装，可以直接对 state 进行赋值，支持深度拷贝，如果直接返回新值会替换原来的 state

请参考文档和使用例子

**Comment by Nodewebzsz** [comment]
`VM1179:1 thirdScriptError 
 sdk uncaught third Error 
 index_js_1.default is not a function 
 TypeError: index_js_1.default is not a function
    at http://127.0.0.1:47502/appservice/store/index.js:35:29
    at require (http://127.0.0.1:47502/appservice/__dev__/WAService.js:22:20279)
    at http://127.0.0.1:47502/appservice/__dev__/WAService.js:22:19993
    at http://127.0.0.1:47502/appservice/app.js:27:18
    at require (http://127.0.0.1:47502/appservice/__dev__/WAService.js:22:20279)
    at http://127.0.0.1:47502/appservice/appservice?t=1531716523190:1259:9`，这个是在ts格式下报的错，在count-demo里面之前的问题都好了，不同的是count-demo里面是js，这个是编译的问题么

**Comment by tolerance-go** [comment]
最好是最小化原则来一步步定位错误，这边不太清楚原因，应该不是代码问题 https://github.com/tolerance-go/weappx/blob/652ddefcebe350659961f0fc69f2df8902282159/packages/weappx/dist/weappx.js#L5783

**Comment by Nodewebzsz** [comment]
我这边把store文件改成js就可以了，应该是ts的exports的问题，具体原因还不清楚

**Comment by zhuanglong** [comment]
这样写成功运行
```javascript
actions: {
    logout() {
      return ({ dispatcher }) => 
        new Promise((resolve) => {
          dispatcher.user.saveCurrentUser({});
          resolve();
        });
    }
}
```
