### ISSUE TITLE
actions ?

### ISSUE THREAD

**Issue by zhuanglong** [tolerance-go/weappx#11]
你好。

文档没有 actions 的实用示例，我这样写是对的吗，按照文档，在 actions 下的函数中获取{ dispatcher, state }，但返回函数的参数为 undefined。

`
...
mutations: {},

actions: {
    getData(obj) {
      console.log(obj); // undefined
    }
}
...
`

**Comment by tolerance-go** [comment]
新增了一个[向导文档](https://github.com/tolerance-go/weappx/blob/master/docs/GUIDE.md#model-%E7%9A%84%E7%BB%93%E6%9E%84)，如果有其他疑问，可以在本 issue 里提出来
