### ISSUE TITLE
wepy1.7.2 + weappx2.0报错 model和视图结合的时候报错

### ISSUE THREAD

**Issue by ranshaw** [tolerance-go/weappx#12]
引入connectPage
<img width="423" alt="11111" src="https://user-images.githubusercontent.com/20283196/42745260-520701ec-8904-11e8-93be-3375119a0359.png">

控制台报错
![222222](https://user-images.githubusercontent.com/20283196/42745271-60206e80-8904-11e8-80ba-895e873f1e7c.png)

是我写的有问题吗？

**Comment by tolerance-go** [comment]
使用 wepy 的话，需要引入 wepy-redux, weappx-weapp 是提供给原生小程序开发使用的

- [demo](https://github.com/tolerance-go/weappx/blob/652ddefcebe350659961f0fc69f2df8902282159/examples/count/src/pages/index.wpy#L39)
- [docs](https://github.com/tolerance-go/weappx/blob/master/docs/API.md#connector)

**Comment by ranshaw** [comment]
已解决，非常感谢，您回复的速度好快哟

**Comment by tolerance-go** [comment]
因为我闲啊。。。
