### ISSUE TITLE
mutations内this无效

### ISSUE THREAD

**Issue by xiaolecn** [tolerance-go/weappx#13]
如图，尝试在mutations内的function调用this，显示undefined
![00](https://user-images.githubusercontent.com/8280724/42928418-d1ea1dba-8b69-11e8-8cdb-b3a7639fd556.png)
![02](https://user-images.githubusercontent.com/8280724/42928421-d29f9ca8-8b69-11e8-9321-f820b98e08dd.png)

**Comment by tolerance-go** [comment]
需求是什么呢？
