### ISSUE TITLE
weappx-plugin-loading 问题

### ISSUE THREAD

**Issue by zhuanglong** [tolerance-go/weappx#17]
已经捕获了异常还是会出现 Uncaught (in promise) 警告，
如果不使用 app.use(createLoading()) 则不会出现

store：
![image](https://user-images.githubusercontent.com/19422011/43933799-6152ee26-9c7e-11e8-9156-5553d16aee2b.png)

![image](https://user-images.githubusercontent.com/19422011/43933821-7e92f120-9c7e-11e8-9a4e-a7afd0eb7580.png)

![image](https://user-images.githubusercontent.com/19422011/43933856-a67b0ec0-9c7e-11e8-9df7-ae8ee882dec4.png)

![image](https://user-images.githubusercontent.com/19422011/43933870-bbb85248-9c7e-11e8-897f-95de93d15457.png)

**Comment by tolerance-go** [comment]
和IDE的es6转换有关系

看截图，是引用 vendor，推测是在原生小程序中遇到的问题

但是IDE的es6转es5不支持async呀，我实际测试的时候用的是下面的写法

```js
actions: {
    a1() {
      return function() {
        return new Promise(function() {
          throw 'test';
        });
      };
    },
  },
```
复现了问题，报错如下
![image](https://user-images.githubusercontent.com/37258382/44148619-a6b4149e-a0cb-11e8-8cfd-b4c6c38e4bf1.png)

的确去除loading插件就没问题了

但是我在 weapp-start 和 wepy 项目里测试后没有发现问题，理论也应该如此，默认的 catch 里直接抛出了 error 

https://github.com/tolerance-go/weappx/blob/a12d60c0f156a74e9d3230332ee8398462ebcbce/packages/weappx/src/index.js#L40 

继续 catch 可以捕获到的，所以比较差异，推测是小程序本身的 IDE 转码问题

建议

暂时放弃loading插件，手动管理；或者关闭IDE转码，使用其他预编译工具

**Comment by zhuanglong** [comment]
@tolerance-go 感谢！
