### ISSUE TITLE
多个model文件，后面model里的store会覆盖前面model里的

### ISSUE THREAD

**Issue by wishinlife** [tolerance-go/weappx#18]
你好，我用微信原生框架开发小程序，用的weappx-weapp，在定义了多个model文件后（每个文件了都执行了 const app = weappx() ），这样会造成先加载的model里的数据丢失，报找不到相关的state，weappx()不是单例的吗？有没有多个model的demo呢？

**Comment by wishinlife** [comment]
你好，我又看了下所有文档，说现在的版本是支持多实例，所以此问题是多实例的问题，哪如何才能在一个connector里来连接不同的实例呢？我看connector源码里是用一个store变量来存储setStore进来的值，这样connector也就只能用一个实例，给使用造成了很大的不便，能否增加在一个页面要访问两个实例的支持。

**Comment by tolerance-go** [comment]
一个实例上可以注册 多个 model 的，一般不需要创建多个实例

**Comment by wishinlife** [comment]
已经解决了，谢谢！
