### ISSUE TITLE
从2.2.3版本API，已经推荐lifetimes来定义生命周期，造成state无效

### ISSUE THREAD

**Issue by wishinlife** [tolerance-go/weappx#19]
从2.2.3版本API，已经推荐lifetimes来定义生命周期，connector中的connectComponent没有对lifetimes做处理，造成如果组件的生命周期函数写在lifetimes中，state无效。改成如下就可以：

> function connectComponent(states = {}, setData = 'setData') {
>   states = normalizeMap(states);
>   return function(ComponentOptions) {
>     let unSubscribe = null;
> 
>     // 生命周期函数，可以为函数，或一个在lifetimes段中定义的方法名
> 	const lifetimes = ComponentOptions.lifetimes || {};
>     const attached = lifetimes.attached || ComponentOptions.attached;
>     const detached = lifetimes.detached || ComponentOptions.detached;
> 
>     lifetimes.attached && delete lifetimes.attached;
>     lifetimes.detached && delete lifetimes.detached;
> 
>     const onStateChange = function() {
>       const newStates = mapState(states);
>       let hasChanged = false;
>       Object.keys(newStates).forEach(k => {
>         const newV = newStates[k];
>         if (!isEqual(this.data[k], newV)) {
>           // 不相等
>           hasChanged = true;
>         }
>       });
>       hasChanged && this[setData](newStates);
>     };
> 
>     return {
>       ...ComponentOptions,
>       data: Object.assign(ComponentOptions.data || {}, mapState(states)),
>       lifetimes: Object.assign(ComponentOptions.lifetimes || {}, {
> 		  attached() {
> 			const store = getStore();
> 			unSubscribe = store.subscribe(onStateChange.bind(this));
> 			onStateChange.call(this);
> 			attached && attached.apply(this, arguments);
> 		  },
> 		  detached() {
> 			unSubscribe && unSubscribe();
> 			unSubscribe = null;
> 			detached && detached.apply(this, arguments);
> 		  },
> 	  })
>     };
>   };
> }

**Comment by tolerance-go** [comment]
https://github.com/tolerance-go/weappx/commit/43318dd306cca67d2886eb0cd9df25dc48f85365
