### ISSUE TITLE
引入最新版进入wepy报错

### ISSUE THREAD

**Issue by smithyj** [tolerance-go/weappx#7]
引入最新版进入wepy报错
![image](https://user-images.githubusercontent.com/9820142/39285461-04cdd138-494b-11e8-85af-7f6bb3ce0a81.png)

**Comment by tolerance-go** [comment]
没有复现成功，不过项目没有依赖 lodash，建议参考 wepy 的[开发文档](https://tencent.github.io/wepy/document.html#/?id=%E6%B7%BB%E5%8A%A0%E9%A1%B9%E7%9B%AE)

**Comment by tolerance-go** [comment]
问题原因：
https://github.com/Tencent/wepy/issues/1276#issuecomment-384539153

暂时解决方法：
https://github.com/Tencent/wepy/issues/1276#issuecomment-384841533
