### ISSUE TITLE
能在京东新出的taro上使用吗？

### ISSUE THREAD

**Issue by ranshaw** [tolerance-go/weappx#9]

**Comment by tolerance-go** [comment]
[weappx@2.x](https://github.com/tolerance-go/weappx/blob/master/docs/WEAPPX2.md) 适配了 taro 这里是 [demo](https://github.com/tolerance-go/weappx/tree/master/examples/count-taro) 感谢 issue

**Comment by ranshaw** [comment]
跑了一遍，小程序上完美，H5还不支持，期待后面的升级哟

**Comment by HuChundong** [comment]
taro的logger是否支持，应当如何使用呢
